/* Brandon Ruger
 * Project 3
 * MiU 1310 */

var json = {
    "reminder1": {
        "petname": ["Pet Name:", "Ryder"],
        "petage": ["Pet Age:", "2"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "Flea Medication"],
        "fleaRx": ["Flea Rx:", "Topical"],
        "heartworm": ["Heartworm:", "No"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/20/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #1"]
    },
    "reminder2": {
        "petname": ["Pet Name:", "Riley"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #2"]
    },
    "reminder3": {
        "petname": ["Pet Name:", "Parker"],
        "petage": ["Pet Age:", "5"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #3"]
    },
    "reminder4": {
        "petname": ["Pet Name:", "Abbey"],
        "petage": ["Pet Age:", "10"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #4"]
    },
    "reminder5": {
        "petname": ["Pet Name:", "Axle"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #5"]
    },
    "reminder6": {
        "petname": ["Pet Name:", "Roxy"],
        "petage": ["Pet Age:", "6"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #6"]
    },
    "reminder7": {
        "petname": ["Pet Name:", "Nemo"],
        "petage": ["Pet Age:", "6"],
        "pettype": ["Pet Type:", "cat"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #7"]
    },
    "reminder8": {
        "petname": ["Pet Name:", "Boo"],
        "petage": ["Pet Age:", "6"],
        "pettype": ["Pet Type:", "cat"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #8"]
    },
    "reminder9": {
        "petname": ["Pet Name:", "Callie"],
        "petage": ["Pet Age:", "3"],
        "pettype": ["Pet Type:", "cat"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #9"]
    },
    "reminder10": {
        "petname": ["Pet Name:", "Booster"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "ferret"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #10"]
    },
    "reminder11": {
        "petname": ["Pet Name:", "Onyx"],
        "petage": ["Pet Age:", "9"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #11"]
    },
    "reminder12": {
        "petname": ["Pet Name:", "Joker"],
        "petage": ["Pet Age:", "4"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #12"]
    },
    "reminder13": {
        "petname": ["Pet Name:", "Buttons"],
        "petage": ["Pet Age:", "8"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #13"]
    },
    "reminder14": {
        "petname": ["Pet Name:", "Amber"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "bird"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #14"]
    },
    "reminder15": {
        "petname": ["Pet Name:", "Max"],
        "petage": ["Pet Age:", "7"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #15"]
    },
    "reminder16": {
        "petname": ["Pet Name:", "Ren"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #16"]
    },
    "reminder17": {
        "petname": ["Pet Name:", "Clue"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "horse"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #17"]
    },
    "reminder18": {
        "petname": ["Pet Name:", "Salem"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "cat"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #18"]
    },
    "reminder19": {
        "petname": ["Pet Name:", "Diesel"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #19"]
    },
    "reminder20": {
        "petname": ["Pet Name:", "Piper"],
        "petage": ["Pet Age:", "1"],
        "pettype": ["Pet Type:", "dog"],
        "flea": ["Flea:", "No"],
        "fleaRx": ["Flea Rx:", "Sprayon"],
        "heartworm": ["Heartworm:", "Heartworm Medication"],
        "other": ["Other:", "No"],
        "date": ["Date:", "9/15/2013"],
        "range": ["Range:", "3"],
        "note": ["Note:", "Reminder #20"]
    },
    
}